apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: springboot-deployment
spec:
  params:
    - name: IMAGE
      description: Image description for Spring Boot backend
      type: string
      default: "alichabchoub/backend:0.0.2"
    - name: TAG
      description: Preferred tag
      default: latest
    - name: MONGO_IMAGE
      description: Image for MongoDB
      type: string
      default: "alichabchoub/mongo:4.4.7"
    - name: FRONTEND_IMAGE
      description: Image for Angular frontend
      type: string
      default: "alichabchoub/angular-app:0.0.3"
  workspaces:
    - name: linked-workspace
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: linked-workspace
      params:
        - name: url
          value: https://github.com/yourusername/your-springboot-app
        - name: subdirectory
          value: ""
        - name: deleteExisting
          value: "true"
    - name: build-push-backend
      taskRef:
        name: buildah
      runAfter:
        - fetch-repository
      workspaces:
        - name: source
          workspace: linked-workspace
      params:
        - name: IMAGE
          value: "$(params.IMAGE):$(params.TAG)"
        - name: CONTEXT
          value: "src"
        - name: FORMAT
          value: "docker"
    - name: build-push-frontend
      taskRef:
        name: buildah
      runAfter:
        - fetch-repository
      workspaces:
        - name: source
          workspace: linked-workspace
      params:
        - name: IMAGE
          value: "$(params.FRONTEND_IMAGE):$(params.TAG)"
        - name: CONTEXT
          value: "front-end"
        - name: FORMAT
          value: "docker"
    - name: create-mongo-deployment
      taskRef:
        name: kubernetes-actions
      runAfter:
        - build-push-backend
      params:
        - name: script
          value: |
            kubectl apply -f your-mongo-deployment.yaml
      workspaces:
        - name: mongo-manifest-dir
          workspace: linked-workspace
    - name: create-deployment
      taskRef:
        name: kubernetes-actions
      runAfter:
        - create-mongo-deployment
        - build-push-frontend
      params:
        - name: script
          value: |
            kubectl apply -f your-springboot-deployment.yaml
            kubectl apply -f your-frontend-deployment.yaml
      workspaces:
        - name: manifest-dir
          workspace: linked-workspace
