apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      volumes:
      - name: mongo-storage
        persistentVolumeClaim:
          claimName: mongo-pvc
      containers:
        - name: mongo
          image: alichabchoub/mongo:4.4.7
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: /data/db
              name: mongo-storage
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  ports:
    - port: 27017
      targetPort: 27017
      nodePort: 30007  # Correction du champ nodePort
  type: NodePort

