apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: frontend-pipelinerun-1
spec:
  serviceAccountName: docker-login
  pipelineRef:
    name: frontend-pipeline
  params:
    - name:  FRONTEND_IMAGE
      value: "alichabchoub/angular-app"
    - name: TAG
      value: latest
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10G